/* 
 * Service Invoice API (api.nfe.io)
 *
 * Seja bem-vindo a documentação do NFe.io!    Nossa API foi criada utilizando o padrão REST que possibilita a integração de seu sistema ao nosso, sendo assim você também pode extender ou   recriar as funcionalidades existentes na nossa plataforma, tudo isso consumindo a API que está documentada abaixo.    ### Como usar a documentação?  Logo a seguir você encontrará todos os recursos e metódos suportados pela API, sendo que essa página possibilita que você teste os recursos e métodos dirementamente através dela.     ### Como funciona a autenticação?  Você precisa de uma **chave de API (API Key)** para identificar a conta que está realizando solicitações para a API. Para isso você deve colocar sua chave de API no campo que se encontra topo desta página para que os métodos funcionem corretamente.  No seu código e integração temos suporte para autenticação de diversas formas sendo eles: **HTTP Header (Authorization ou X-NFEIO-APIKEY)** ou **HTTP Query String (api_key)** nos dois modos passando o valor da sua chave de api (API Key).  
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NaturalPeopleApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class NaturalPeopleApiTests
    {
        private NaturalPeopleApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NaturalPeopleApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NaturalPeopleApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' NaturalPeopleApi
            //Assert.IsInstanceOfType(typeof(NaturalPeopleApi), instance, "instance is a NaturalPeopleApi");
        }

        
        /// <summary>
        /// Test NaturalPeopleGet
        /// </summary>
        [Test]
        public void NaturalPeopleGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string companyId = null;
            //var response = instance.NaturalPeopleGet(companyId);
            //Assert.IsInstanceOf<NaturalPersonCollectionResource> (response, "response is NaturalPersonCollectionResource");
        }
        
        /// <summary>
        /// Test NaturalPeopleGet_0
        /// </summary>
        [Test]
        public void NaturalPeopleGet_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string companyId = null;
            //string id = null;
            //var response = instance.NaturalPeopleGet_0(companyId, id);
            //Assert.IsInstanceOf<NaturalPersonResource> (response, "response is NaturalPersonResource");
        }
        
    }

}
